import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: 'Yuliya Tverdokhlib',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.svg',
  },
};

const hostGrotesk = localFont({
  src: './fonts/HostGrotesk.ttf',
  display: 'swap',
  variable: '--font-host-grotesk',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={hostGrotesk.variable}>
      <body className={hostGrotesk.className + 'antialiased'}>{children}</body>
    </html>
  );
}
